// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPhP8iiE977O8R4BrLYOTs9gXvhpaU0nY',
    appId: '1:183434543868:web:5c37893813ea3cc5850d79',
    messagingSenderId: '183434543868',
    projectId: 'easy-pay-fba8c',
    authDomain: 'easy-pay-fba8c.firebaseapp.com',
    storageBucket: 'easy-pay-fba8c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyokosXFva3AMPjqm-n5i1pjMkXp6zYU8',
    appId: '1:183434543868:android:13df4b7f69344746850d79',
    messagingSenderId: '183434543868',
    projectId: 'easy-pay-fba8c',
    storageBucket: 'easy-pay-fba8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZbs-Rf-uHx3qvWjgR1hMWeCjECbzNqxU',
    appId: '1:183434543868:ios:6abf08b54c1db525850d79',
    messagingSenderId: '183434543868',
    projectId: 'easy-pay-fba8c',
    storageBucket: 'easy-pay-fba8c.firebasestorage.app',
    iosBundleId: 'org.campusniger.easypay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZbs-Rf-uHx3qvWjgR1hMWeCjECbzNqxU',
    appId: '1:183434543868:ios:6abf08b54c1db525850d79',
    messagingSenderId: '183434543868',
    projectId: 'easy-pay-fba8c',
    storageBucket: 'easy-pay-fba8c.firebasestorage.app',
    iosBundleId: 'org.campusniger.easypay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPhP8iiE977O8R4BrLYOTs9gXvhpaU0nY',
    appId: '1:183434543868:web:6491c2d98d5c1925850d79',
    messagingSenderId: '183434543868',
    projectId: 'easy-pay-fba8c',
    authDomain: 'easy-pay-fba8c.firebaseapp.com',
    storageBucket: 'easy-pay-fba8c.firebasestorage.app',
  );

}